"""Add email and prep_time_minutes

Revision ID: 3c42bcca272b
Revises: 
Create Date: 2026-04-05 20:55:51.539633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c42bcca272b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('prep_time_minutes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('menu_items', 'prep_time_minutes')
    # ### end Alembic commands ###
